# Generated by Django 5.2.4 on 2025-08-10 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('date_of_registration', models.DateField()),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('registration_certificate', models.FileField(upload_to='ngo_docs/registration/')),
                ('certificate_80g', models.FileField(blank=True, null=True, upload_to='ngo_docs/80g/')),
                ('certificate_12a', models.FileField(blank=True, null=True, upload_to='ngo_docs/12a/')),
                ('pan_card', models.FileField(upload_to='ngo_docs/pan/')),
                ('aadhaar_card', models.FileField(upload_to='ngo_docs/aadhaar/')),
                ('annual_report', models.FileField(blank=True, null=True, upload_to='ngo_docs/annual_report/')),
                ('bank_statement', models.FileField(upload_to='ngo_docs/bank_statement/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
