# Generated by Django 5.2.4 on 2025-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_favicon/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
