# Generated by Django 5.2.4 on 2025-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
