# Generated by Django 5.2.4 on 2025-08-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0005_alter_foodpost_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='contact',
        ),
        migrations.AddField(
            model_name='foodpost',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('canned', 'Canned Goods'), ('snacks', 'Snacks')], default='fruits', max_length=50),
        ),
        migrations.AddField(
            model_name='foodpost',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodpost',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='food_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
