# Generated by Django 5.2.4 on 2025-08-10 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0006_remove_foodpost_contact_foodpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
