# Generated by Django 5.2.4 on 2025-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0008_category_alter_foodpost_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='contact',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
