# Generated by Django 5.2.4 on 2025-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0009_foodpost_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
