# Generated by Django 5.2.4 on 2025-08-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0010_alter_foodpost_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
    ]
