# Generated by Django 5.2.4 on 2025-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0011_alter_foodpost_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='status',
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
