# Generated by Django 5.2.4 on 2025-08-10 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0012_remove_foodpost_status_alter_foodpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leftoverlink_app.category'),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
