# Generated by Django 5.2.4 on 2025-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0013_alter_foodpost_category_alter_foodpost_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
