# Generated by Django 5.2.4 on 2025-08-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leftoverlink_app', '0019_remove_userprofile_is_verified_ngoprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
